"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, ExternalLink, FileText, Info, ShieldCheck } from "lucide-react";
import { useState } from "react";
import type { ServiceGuide as ServiceGuideType } from "@/data/services";
import { ExplainThis } from "./explain-this";
import { ReadAloud } from "./read-aloud";

export function ServiceGuide({ service }: { service: ServiceGuideType }) {
  const [step, setStep] = useState(0);
  const active = service.steps[step];
  const term = active.term ? service.terms.find((item) => item.term === active.term) : undefined;
  return <div className="page guide-page"><div className="guide-top"><Link href="/services" className="back-link"><ArrowLeft size={19} /> All services</Link><p className="demo-label"><Info size={16} /> Guidance / demonstration</p></div><header className="guide-header"><p className="eyebrow">UNDERSTANDING</p><h1>{service.title}</h1><p>{service.summary}</p></header><div className="guide-layout"><aside className="guide-overview"><section><FileText size={22} /><h2>What is this?</h2><p>{service.whatIsIt}</p></section><section><CheckCircle2 size={22} /><h2>Who might need it?</h2><p>{service.whoMightNeedIt}</p></section><section><h2>What might you need?</h2><ul className="document-list">{service.documents.map((item) => <li key={item.name}><details><summary><span><Check size={17} /> {item.name}</span><ChevronDown size={18} /></summary><p><strong>What is this?</strong> {item.explanation}</p></details></li>)}</ul></section></aside><section className="guide-workflow" aria-live="polite"><div className="step-progress"><span>STEP {step + 1} OF {service.steps.length}</span><div aria-hidden="true">{service.steps.map((_, index) => <i key={index} className={index <= step ? "complete" : ""} />)}</div></div><p className="eyebrow">ONE STEP AT A TIME</p><h2>{active.title}</h2><p className="step-body">{active.body}</p>{active.note && <aside className="step-note"><Info size={20} /><span>{active.note}</span></aside>}{term && <ExplainThis source={term.source} fallback={{ simple: term.simple, why: term.why }} />}<ReadAloud text={`${active.title}. ${active.body} ${active.note ?? ""}`} /><div className="step-actions"><button type="button" className="secondary-button" disabled={step === 0} onClick={() => setStep((value) => value - 1)}><ArrowLeft size={19} /> Back</button>{step < service.steps.length - 1 ? <button type="button" className="primary-button" onClick={() => setStep((value) => value + 1)}>Next <ArrowRight size={19} /></button> : <a className="primary-button" href="https://www.india.gov.in/" target="_blank" rel="noreferrer">Visit official source <ExternalLink size={18} /></a>}</div></section></div><section className="official-source"><div><p className="eyebrow"><ShieldCheck size={16} /> OFFICIAL SOURCE</p><h2>Continue only when you are ready.</h2><p>{service.sourceLabel}</p><small>SAHAY explains the process. The official website handles the actual application and has the current information.</small></div><a href="https://www.india.gov.in/" target="_blank" rel="noreferrer" className="secondary-button">Visit the official website <ExternalLink size={18} /></a></section></div>;
}
