"use client";

import Link from "next/link";
import { Check, CircleGauge, Contrast, Languages, MousePointer2, Volume2 } from "lucide-react";
import { useAccessibility } from "@/components/accessibility-provider";
import { languages } from "@/data/translations";
import { promptTemplates } from "@/lib/ai";

export default function AccessibilityPage() {
  const { textSize, setTextSize, highContrast, setHighContrast, simpleMode, setSimpleMode, reduceMotion, setReduceMotion, language, setLanguage } = useAccessibility();
  const features = [{ icon: CircleGauge, title: "Text size", text: "Make type larger across the whole experience.", control: <div className="inline-choice">{(["normal", "large", "xlarge"] as const).map((value) => <button type="button" className={textSize === value ? "selected" : ""} onClick={() => setTextSize(value)} key={value}>{value === "xlarge" ? "A++" : value === "large" ? "A+" : "A"}</button>)}</div> }, { icon: Contrast, title: "High contrast", text: "Stronger borders and clearer text.", control: <button type="button" className={highContrast ? "toggle-button selected" : "toggle-button"} onClick={() => setHighContrast(!highContrast)}>{highContrast ? "On" : "Off"}</button> }, { icon: MousePointer2, title: "Simple mode", text: "Fewer choices and a clearer primary task.", control: <button type="button" className={simpleMode ? "toggle-button selected" : "toggle-button"} onClick={() => setSimpleMode(!simpleMode)}>{simpleMode ? "On" : "Off"}</button> }, { icon: Volume2, title: "Read aloud", text: "Use your browser’s built-in speech controls where available.", control: <span className="status-label">Available on guides</span> }, { icon: CircleGauge, title: "Reduce motion", text: "Limit non-essential transitions and movement.", control: <button type="button" className={reduceMotion ? "toggle-button selected" : "toggle-button"} onClick={() => setReduceMotion(!reduceMotion)}>{reduceMotion ? "On" : "Off"}</button> }, { icon: Languages, title: "Language", text: "Choose English, Tamil, or Hindi for SAHAY interface labels.", control: <select aria-label="Language" value={language} onChange={(e) => setLanguage(e.target.value as typeof language)}>{languages.map((item) => <option value={item.code} key={item.code}>{item.native}</option>)}</select> }];
  return <div className="page inner-page"><header className="page-header"><p className="eyebrow">YOUR CONTROL</p><h1>Accessibility, built into the experience.</h1><p>Use the controls at any time. Your settings are saved only in this browser.</p></header><section className="accessibility-grid">{features.map(({ icon: Icon, title, text, control }) => <article key={title} className="accessibility-card"><Icon size={28} /><h2>{title}</h2><p>{text}</p>{control}</article>)}</section><section className="prompt-docs"><div><p className="eyebrow">AI PROMPT DOCUMENTATION</p><h2>Designed to explain, not to guess.</h2><p>Each response is structured to reduce jargon, make uncertainty clear, and keep the official source separate from SAHAY’s explanation.</p></div><div className="prompt-list">{Object.entries(promptTemplates).slice(0, 4).map(([key, prompt]) => <article key={key}><h3>{key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase())}</h3><p><strong>Prompt:</strong> {prompt}</p><small><Check size={16} /> Accessibility consideration: short, clear language and no invented requirements.</small></article>)}</div></section><div className="centered-action"><Link href="/audit" className="primary-button">Open the accessibility audit</Link></div></div>;
}
